# Generated by Django 4.1.1 on 2022-10-04 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('image', models.CharField(max_length=100, verbose_name='Фото')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('tv', 'Телевизор'), ('Smartphone', 'Смартфон'), ('Laptop', 'Ноутбук')], default='other', max_length=50, verbose_name='Категория')),
                ('balance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('category', 'name'),
            },
        ),
    ]
